import { Metadata } from "next"
import Sidebar from "./components/Sidebar"
import { Toaster } from "sonner"
import { getStays } from "@/utils/helpers";
import PopCalendar from "./components/calendar/PopCalendar";

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
    alternates: {
        canonical: 'https://pabloranea.com/en',
    },
}

export default function layout({ children }: { children: React.ReactNode }) {

    return (
        <div className="h-screen flex w-full relative">
            <Sidebar />
            {children}
            <PopCalendar />
            <Toaster />
        </div>
    )
}
