import { Metadata } from "next"
import Navbar from "./components/Navbar"
import Sidebar from "./components/Sidebar"

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
}

export default function layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="h-screen">
            <Navbar />
            <div className="grid grid-cols-12 w-full h-full">
                <Sidebar />
                {children}
            </div>
        </div>
    )
}
