import { Metadata } from "next"
import Sidebar from "./components/Sidebar"

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
}

export default function layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="h-screen flex">
            <Sidebar />
            {children}
        </div>
    )
}
