import { Metadata } from "next"
import Sidebar from "./components/Sidebar"
import { Toaster } from "sonner"

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
}

export default function layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="h-screen flex w-full">
                <Sidebar />
                {children}
                <Toaster />
        </div>
    )
}
